// <auto-generated />
namespace CRUD_Owners_RealState.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RenameOwnerID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameOwnerID));
        
        string IMigrationMetadata.Id
        {
            get { return "202410122022158_RenameOwnerID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
