// <auto-generated />
namespace CRUD_Owners_RealState.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class PropertyFKOwnerIdNullableAndDeleteCascadeFalse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropertyFKOwnerIdNullableAndDeleteCascadeFalse));
        
        string IMigrationMetadata.Id
        {
            get { return "202410161233316_PropertyFKOwnerIdNullableAndDeleteCascadeFalse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
