// <auto-generated />
namespace CRUD_Owners_RealState.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class OwnerRelationWithNominee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OwnerRelationWithNominee));
        
        string IMigrationMetadata.Id
        {
            get { return "202410122028527_OwnerRelationWithNominee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
